C_TYPE_CHARACTER=1
C_DIR_UP=1
C_DIR_DOWN=2
C_DIR_LEFT=3
C_DIR_RIGHT=4

#~ C_USER_WIDTH=1280
#~ C_USER_HEIGHT=720
C_USER_WIDTH=1600
C_USER_HEIGHT=900
#~ C_USER_WIDTH=300
#~ C_USER_HEIGHT=400
C_RATIO_X=float(float(C_USER_WIDTH)/float(C_USER_HEIGHT))
#~ C_RATIO_Z=float(float(C_USER_HEIGHT)/float(C_USER_WIDTH))

C_ITEM_WEAPON=1
C_ITEM_ARMOR=2
C_ITEM_POTION=3

C_ITEM_WEAPON_CONTACT=1
C_ITEM_WEAPON_ARC=2
C_ITEM_WEAPON_WAND=3

C_ITEM_POTION_LIFE=1

C_SLOT_LEFT=1
C_SLOT_MIDDLE=2
C_SLOT_RIGHT=3
C_SLOT_GLOVE=4
C_SLOT_FEET=5
C_SLOT_HEAD=6
C_SLOT_EXTERNAL=10

C_CARAC_FORCE=1
C_CARAC_DEXTERITE=2
C_CARAC_CONSTITUTION=3
C_CARAC_INTELLIGENCE=4
C_CARAC_CHANCE=5

C_CLASS_WARRIOR=1
C_CLASS_ROGUE=2
C_CLASS_WIZARD=3

C_BONUS_FORCE=1
C_BONUS_DEXTERITE=2
C_BONUS_INTELLIGENCE=3
C_BONUS_CONSTITUTION=4
C_BONUS_CHANCE=5
C_BONUS_DEGAT=6
C_BONUS_PORTEE=7
C_BONUS_VITESSE=8
C_BONUS_ARMOR=9